### ISSUE TITLE
api.recieve方法是什么？

### ISSUE THREAD

**Issue by oikewll** [scbrf/scbrf#1]
看到挂了一个全局的api，但是看不到在哪
api 返回undefined

**Comment by scbrf** [comment]
在根路径有个preload.js，api是inject进入的。

> const { ipcRenderer, contextBridge } = require('electron')
contextBridge.exposeInMainWorld('api', {
  send: (channel, data) => ipcRenderer.send(channel, data),
  recieve: (channel, func) => ipcRenderer.on(channel, (event, ...args) => func(args)),
  invoke() {
    return ipcRenderer.invoke(...arguments)
  },
})
